services:
  backend:
    build:
      context: .
    container_name: backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pokedex
      - SPRING_DATASOURCE_USERNAME=pokedex
      - SPRING_DATASOURCE_PASSWORD=pokedex
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    build:
      context: src/main/frontend/
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  db:
    image: 'postgres:alpine'
    container_name: db
    environment:
      - POSTGRES_USER=pokedex
      - POSTGRES_PASSWORD=pokedex